# ======================== Elasticsearch Configuration =========================
#
# NOTE: Elasticsearch comes with reasonable defaults for most settings.
#       Before you set out to tweak and tune the configuration, make sure you
#       understand what are you trying to accomplish and the consequences.
#
# The primary way of configuring a node is via this file. This template lists
# the most important settings you may want to configure for a production cluster.
#
# Please see the documentation for further information on configuration options:
# <https://www.elastic.co/guide/en/elasticsearch/reference/5.0/settings.html>
#
# ---------------------------------- Cluster -----------------------------------
#
# Use a descriptive name for your cluster:
#
#cluster.name: my-application
#
# ------------------------------------ Node ------------------------------------
#
# Use a descriptive name for the node:
#
#node.name: node-1
#
# Add custom attributes to the node:
#
#node.attr.rack: r1
#
# ----------------------------------- Paths ------------------------------------
#
# Path to directory where to store the data (separate multiple locations by comma):
#
#path.data: /path/to/data
#
# Path to log files:
#
#path.logs: /path/to/logs
#
# ----------------------------------- Memory -----------------------------------
#
# Lock the memory on startup:
#
#bootstrap.memory_lock: true
#
# Make sure that the heap size is set to about half the memory available
# on the system and that the owner of the process is allowed to use this
# limit.
#
# Elasticsearch performs poorly when the system is swapping the memory.
#
# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
#network.host: 192.168.0.1
#
# Set a custom port for HTTP:
#
#http.port: 9200
#
# For more information, see the documentation at:
# <https://www.elastic.co/guide/en/elasticsearch/reference/5.0/modules-network.html>
#
# --------------------------------- Discovery ----------------------------------
#
# Pass an initial list of hosts to perform discovery when new node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
#
#discovery.zen.ping.unicast.hosts: ["host1", "host2"]
#
# Prevent the "split brain" by configuring the majority of nodes (total number of nodes / 2 + 1):
#
#discovery.zen.minimum_master_nodes: 3
#
# For more information, see the documentation at:
# <https://www.elastic.co/guide/en/elasticsearch/reference/5.0/modules-discovery-zen.html>
#
# ---------------------------------- Gateway -----------------------------------
#
# Block initial recovery after a full cluster restart until N nodes are started:
#
#gateway.recover_after_nodes: 3
#
# For more information, see the documentation at:
# <https://www.elastic.co/guide/en/elasticsearch/reference/5.0/modules-gateway.html>
#
# ---------------------------------- Various -----------------------------------
#
# Require explicit names when deleting indices:
#
#action.destructive_requires_name: true
#

 #集群名称，以此作为是否同一个集群的判断条件
 cluster.name: jq-2018
 #节点名称：以此作为集群中不同节点的区分条件
 node.name: node_01
 #是否指定该节点为master
 node.master: true

 #node.data: true

 #数据存储地址
 path.data: /usr/share/elasticsearch/data
 #日志存储地址
 path.logs: /usr/share/elasticsearch/logs

 # 内网地址，可以加快速度
 network.host: 0.0.0.0
 #网络地址和端口，用于http和transport服务使用
 http.port: 9200
 network.publish_host: 118.31.237.102

 transport.tcp.port: 9300


 #index.refresh_interval: 5s
 #script.inline: true
 #script.indexed: true

 #discovery.zen.ping.unicast.hosts: ["10.80.176.35:9301", "10.80.109.218:9301"]
 #discovery.zen.minimum_master_nodes: 1     # 由于只部署两个节点，因此设置为1，否则当master宕机，将无法重新选取master
# 以下配置可以减少当es节点短时间宕机或重启时shards重新分布带来的磁盘io读写浪费
 #discovery.zen.fd.ping_timeout: 180s
 #discovery.zen.fd.ping_retries: 8
 #discovery.zen.fd.ping_interval: 30s
 #discovery.zen.ping_timeout: 120s

# 增加新的参数，这样head插件可以访问es
 http.cors.enabled: true
 http.cors.allow-origin: "*"
